INSERT INTO produttore (nome)
VALUES
	('3xE - electric cars'),
	('Alkè'),
	('American Electric'),
	('Amp Electric Vehicles'),
	('Aptera Motors'),
	('Arcimoto'),
	('ATT R&D'),
	('Audi'),
	('Automobiles Chatenet'),
	('BAIC'),
	('Balqon'),
	('Beepo'),
	('Bluebird Automotive'),
	('BMW'),
	('BMW i'),
	('Boeing'),
	('Buddy Electric'),
	('BYD Auto'),
	('Chery Automobile Co'),
	('Citroen'),
	('Citysax'),
	('Coda Automotive'),
	('Commuter Cars'),
	('Compagnie Centrale des Transports Automobiles'),
	('Detroit Electric'),
	('DOK-ING'),
	('Duracar'),
	('Dynasty Electric Vehicle Ltd.'),
	('e-Wolf GmbH'),
	('ECOmove'),
	('Electric Vehicles International'),
	('Fam Auto'),
	('FINE Mobile GmbH - The TWIKE Manufacturer'),
	('Fisker Automotive'),
	('Ford'),
	('GEM'),
	('General Motors'),
	('GGT Electric'),
	('Ginetta'),
	('Green Vehicles'),
	('Greenlinecars'),
	('Heuliez'),
	('Hiriko'),
	('Honda'),
	('Hyundai'),
	('Kia'),
	('Lightning Car Company'),
	('Loremo'),
	('LUIS'),
	('Lumeneo'),
	('Luxgen'),
	('Maranello 4cycle'),
	('Mercedes-Benz'),
	('mia electric'),
	('Miles Electric Vehicles'),
	('Mitsubishi'),
	('Myers Motors'),
	('Nice Car Company'),
	('Nissan'),
	('Oka Auto'),
	('Opel'),
	('Optimal Energy'),
	('Peugeot'),
	('Phoenix Motorcars'),
	('Pininfarina'),
	('Protoscar'),
	('Pure Mobility'),
	('Renault'),
	('Reva'),
	('Rinspeed'),
	('Rolls Royce'),
	('S.A.M. Group AG'),
	('SABA'),
	('SAIC'),
	('SEAT'),
	('Sim'),
	('SIMPLYCITY'),
	('Smart'),
	('Smiles AG'),
	('Smith Electric'),
	('Star Electric Vehicles'),
	('Subaru'),
	('Tazzari'),
	('TE'),
	('Tesla Motors'),
	('THEKPV'),
	('Think'),
	('Tilter - SynergEthic'),
	('Toyota'),
	('Trabant'),
	('Volkswagen'),
	('Volvo'),
	('Wheego'),
	('Wrightspeed'),
	('Zap'),
	('ZEV Motors');
