CREATE TABLE "Produttore"
(
  "Nome" CHARACTER VARYING NOT NULL,
  CONSTRAINT "Produttore_pkey" PRIMARY KEY ("Nome" )
);
 

insert into produttore(nome)
values
('3xE - electric cars'),
('Alk&egrave;'),
('Alk&egrave;'),
('Alk&egrave;'),
('American Electric'),
('Amp Electric Vehicles'),
('Amp Electric Vehicles'),
('Amp Electric Vehicles'),
('Amp Electric Vehicles'),
('Amp Electric Vehicles'),
('Aptera Motors'),
('Arcimoto'),
('ATT R&amp;D'),
('ATT R&amp;D'),
('ATT R&amp;D'),
('ATT R&amp;D'),
('Audi'),
('Audi'),
('Audi'),
('Audi'),
('Automobiles Chatenet'),
('BAIC'),
('Balqon'),
('Balqon'),
('Balqon'),
('Beepo'),
('Bluebird Automotive'),
('BMW'),
('BMW'),
('BMW'),
('BMW i'),
('BMW i'),
('Boeing'),
('Buddy Electric'),
('BYD Auto'),
('BYD Auto'),
('BYD Auto'),
('BYD Auto'),
('Chery Automobile Co'),
('Citroen'),
('Citroen'),
('Citysax'),
('Coda Automotive'),
('Commuter Cars'),
('Compagnie Centrale des Transports Automobiles'),
('Detroit Electric'),
('Detroit Electric'),
('DOK-ING'),
('Duracar'),
('Dynasty Electric Vehicle Ltd.'),
('Dynasty Electric Vehicle Ltd.'),
('Dynasty Electric Vehicle Ltd.'),
('Dynasty Electric Vehicle Ltd.'),
('Dynasty Electric Vehicle Ltd.'),
('e-Wolf GmbH'),
('e-Wolf GmbH'),
('e-Wolf GmbH'),
('e-Wolf GmbH'),
('e-Wolf GmbH'),
('e-Wolf GmbH'),
('e-Wolf GmbH'),
('e-Wolf GmbH'),
('ECOmove'),
('Electric Vehicles International'),
('Electric Vehicles International'),
('Electric Vehicles International'),
('Fam Auto'),
('FINE Mobile GmbH - The TWIKE Manufacturer'),
('FINE Mobile GmbH - The TWIKE Manufacturer'),
('Fisker Automotive'),
('Ford'),
('GEM'),
('GEM'),
('GEM'),
('GEM'),
('GEM'),
('GEM'),
('General Motors'),
('GGT Electric'),
('GGT Electric'),
('Ginetta'),
('Green Vehicles'),
('Green Vehicles'),
('Greenlinecars'),
('Heuliez'),
('Hiriko'),
('Honda'),
('Honda'),
('Hyundai'),
('Kia'),
('Kia'),
('Lightning Car Company'),
('Loremo'),
('LUIS'),
('Lumeneo'),
('Lumeneo'),
('Luxgen'),
('Maranello 4cycle'),
('Mercedes-Benz'),
('Mercedes-Benz'),
('Mercedes-Benz'),
('Mercedes-Benz'),
('mia electric'),
('mia electric'),
('mia electric'),
('Miles Electric Vehicles'),
('Miles Electric Vehicles'),
('Mitsubishi'),
('Myers Motors'),
('Nice Car Company'),
('Nissan'),
('Oka Auto'),
('Opel'),
('Optimal Energy'),
('Peugeot'),
('Peugeot'),
('Phoenix Motorcars'),
('Pininfarina'),
('Pininfarina'),
('Protoscar'),
('Protoscar'),
('Pure Mobility'),
('Renault'),
('Renault'),
('Renault'),
('Renault'),
('Reva'),
('Reva'),
('Reva'),
('Rinspeed'),
('Rolls Royce'),
('S.A.M. Group AG'),
('SABA'),
('SAIC'),
('SEAT'),
('Sim'),
('SIMPLYCITY'),
('SIMPLYCITY'),
('SIMPLYCITY'),
('SIMPLYCITY'),
('SIMPLYCITY'),
('SIMPLYCITY'),
('Smart'),
('Smiles AG'),
('Smith Electric'),
('Smith Electric'),
('Star Electric Vehicles'),
('Star Electric Vehicles'),
('Star Electric Vehicles'),
('Star Electric Vehicles'),
('Subaru'),
('Subaru'),
('Tazzari'),
('TE'),
('Tesla Motors'),
('Tesla Motors'),
('Tesla Motors'),
('THEKPV'),
('Think'),
('Tilter - SynergEthic'),
('Toyota'),
('Toyota'),
('Trabant'),
('Volkswagen'),
('Volkswagen'),
('Volvo'),
('Wheego'),
('Wrightspeed'),
('Zap'),
('Zap'),
('Zap'),
('Zap'),
('Zap'),
('Zap'),
('ZEV Motors'),
('ZEV Motors'),
('ZEV Motors'),
('ZEV Motors'),
('ZEV Motors'),
('ZEV Motors'),
('ZEV Motors'),
('ZEV Motors');
